# Generated by Django 2.1.2 on 2018-10-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('poster', models.TextField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('release_date', models.DateTimeField(null=True)),
                ('keywords', models.TextField(null=True)),
                ('genres', models.TextField(null=True)),
                ('production_companies', models.TextField(null=True)),
                ('cast', models.TextField(null=True)),
                ('directors', models.TextField(null=True)),
                ('soup', models.TextField(null=True)),
            ],
        ),
    ]
